version: '3.2'
services:
    web-1:
      image: nicopaez/password-api
    web-2:
      image: nicopaez/password-api
    loadbalancer:
      image: nginx:latest
      volumes:
        ./nginx:/etc/nginx/conf.d
     
      ports:
        - '80:80'
          
      depends_on:
        - web-1
        - web-2



